# Generated by Django 4.2.3 on 2023-08-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
